type Users {
    email: String! @unique
    firstname: String!
    lastname: String!
    password: String!
    userReadOnlyOne: String
    userReadOnlyTwo: String
    userReadOnlyThree: String
    adminAccessOnlyOne: String
    adminAccessOnlyTwo: String
    adminAccessOnlyThree: String
}

type Admins {
    email: String! @unique
    password: String!
    firstname: String!
    lastname: String!
}

type Query {
    allUsers: [Users!]!
    allAdmins: [Admins!]!
    loginUser(email: String!, password: String!): Users
    loginAdmin(email: String!, password: String!): Admins
}
