type User {
    email: String! @unique
    password: String!
    firstname: String!
    lastname: String!
    userReadOnlyOne: String
    userReadOnlyTwo: String
    userReadOnlyThree: String
    adminAccessOnlyOne: String
    adminAccessOnlyTwo: String
    adminAccessOnlyThree: String
}


type Admin {
    email: String! @unique
    password: String!
}
    
type Query {
    allUsers: [User!]!
    allAdmins: [Admin!]!
}